// Code generated by goctl. DO NOT EDIT!
// Source: usrpc.proto

package server

import (
	"context"

	"wow_server/userrpc/internal/logic"
	"wow_server/userrpc/internal/svc"
	"wow_server/userrpc/usrpc"
)

type UsrpcServer struct {
	svcCtx *svc.ServiceContext
	usrpc.UnimplementedUsrpcServer
}

func NewUsrpcServer(svcCtx *svc.ServiceContext) *UsrpcServer {
	return &UsrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UsrpcServer) Ping(ctx context.Context, in *usrpc.Request) (*usrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
