// Code generated by goctl. DO NOT EDIT!
// Source: usrpc.proto

package usrpcclient

import (
	"context"

	"wow_server/userrpc/usrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = usrpc.Request
	Response = usrpc.Response

	Usrpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUsrpc struct {
		cli zrpc.Client
	}
)

func NewUsrpc(cli zrpc.Client) Usrpc {
	return &defaultUsrpc{
		cli: cli,
	}
}

func (m *defaultUsrpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := usrpc.NewUsrpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
